### ISSUE TITLE
utilizes an UVC USB camera

### ISSUE THREAD

**Issue by tlkw79** [sajmons/CollimationCircles#11]
Hi,

Thanks for the great app here. Is it possible to include a UVC USB camera in your app?  For an example, [https://github.com/edu27/pyReflectorCollimator](url)

Regards,
Tom

**Comment by sajmons** [comment]
In feature release I'm planing to support displaying camera sttream in window background. But user will still need to provide stream by himself.

**Comment by tlkw79** [comment]
That's great! Can't wait for it.

**Comment by tlkw79** [comment]
By the way, are you planning to release an Android version or ipad version?

**Comment by sajmons** [comment]
Android and iPad versions are not planed for now. Maybe in the future if enough users will show interest in it. AvaloniaUI technology has support for both Android and iOS.

**Comment by tlkw79** [comment]
> Android and iPad versions are not planed for now. Maybe in the future if enough users will show interest in it. AvaloniaUI technology has support for both Android and iOS.

There is an android app called OpenLiveStacker is welcoming other developer to collaborate with it.  

[https://github.com/artyom-beilis/OpenLiveStacker](url)

Tom

**Comment by sajmons** [comment]
UVC and Rasperry Pi camera stream now available. Closing
