### ISSUE TITLE
No camera under Ubuntu 22.04

### ISSUE THREAD

**Issue by zsarosi** [sajmons/CollimationCircles#20]
Hi!
First, many thanks for the excellent app, and that you made it also for Linux users available!
I am using Ubuntu 22.04 with multiple cameras: Lenovo Notebook builtin, old Logitech Quickcam Pro for notebook using UVC and Sony A6500 over gphoto2.
I downloaded the current binary version (3.2.0.0. beta3) of the software and started it. Now the software starts without problems, but the list of available cameras is empty. I tried to use the remote field, and I defined there /dev/video0 .. video4, but it didn't react. 
Is it a bug, or am I doing something false? Other applications like zoom, vlc, guvcview can use the camera stream.
However, it is not a show stopper in my case, as I can open the camera stream in an other app and I just overlay the transparent CollimationCircles window on them, but it would be more elegant/simple to use the camera stream directly from the app.

Thanks!
Zoltan

**Comment by zsarosi** [comment]
For sure. I just checked the logs myself, and I found a hint, the v4l-utils was not installed, so I installed it, an now it finds my Notebook integrated camera, but not the UVC one. Maybe I am doing it wrong:I start the guvcview app, that starts the video stream, but the CollimationCircles (after restart) cannot see the UVC camera stream. (see the logs in the attachment)
[CC_Log.2024-04-25.txt](https://github.com/sajmons/CollimationCircles/files/15110451/CC_Log.2024-04-25.txt)

**Comment by sajmons** [comment]
@zsarosi indead there was a little bug in camera detecting code! Thank you for finding this!
There is new beta4 release https://github.com/sajmons/CollimationCircles/releases/tag/version-3.2.0-beta4.
Let me know if now detects your UVC camera.

**Comment by sajmons** [comment]
> Hi! First, many thanks for the excellent app, and that you made it also for Linux users available! I am using Ubuntu 22.04 with multiple cameras: Lenovo Notebook builtin, old Logitech Quickcam Pro for notebook using UVC and Sony A6500 over gphoto2. I downloaded the current binary version (3.2.0.0. beta3) of the software and started it. Now the software starts without problems, but the list of available cameras is empty. I tried to use the remote field, and I defined there /dev/video0 .. video4, but it didn't react. Is it a bug, or am I doing something false? Other applications like zoom, vlc, guvcview can use the camera stream. However, it is not a show stopper in my case, as I can open the camera stream in an other app and I just overlay the transparent CollimationCircles window on them, but it would be more elegant/simple to use the camera stream directly from the app.
> 
> Thanks! Zoltan

Remote option is meant for playable remote streams. For example someone (or you) create camera stream on remote computer and give you http URL of that stream. Then you chose remote option and enter full http url of that stream. For example: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4.

**Comment by zsarosi** [comment]
Hi @sajmons 
Many thanks for the fix, the camera works finally!
The only problem, that the camera controls do not seem to work properly: not all of the gauges work, for example gain, exposure time, gamma, saturation, hue, contrast do not work. In case of saturation it is not a real issue, grayscale is just fine. Interestingly, if I start the camera with the guvc viewer app, then I can adjust the picture parameters, then end the app and start CollimationCircles, then I have a good image, that I can use.

**Comment by sajmons** [comment]
> Hi @sajmons Many thanks for the fix, the camera works finally! The only problem, that the camera controls do not seem to work properly: not all of the gauges work, for example gain, exposure time, gamma, saturation, hue, contrast do not work. In case of saturation it is not a real issue, grayscale is just fine. Interestingly, if I start the camera with the guvc viewer app, then I can adjust the picture parameters, then end the app and start CollimationCircles, then I have a good image, that I can use.

Yeah, camera controls are next thing I have to review. When I have time, I will and then you can expect some improvements.

**Comment by zsarosi** [comment]
Ok, many thanks! I close the ticket now, as I see there is already an open issue regarding UVC camera control.
