### ISSUE TITLE
app works with macOS 11.7, but it is tagged for 12 in info.plist

### ISSUE THREAD

**Issue by jordisese** [sajmons/CollimationCircles#22]
First of all, thanks for building this app and making it available.

The fact is that this App works fine with MacOS 11.X, but it is tagged for 12 in every MacOS release package since they are built.

I have edited the file Info.plist in the App package and have changed the 
**LSMinimumSystemVersion** key value from 12 to 11 and now it works perfectly with my 11.7 (Big Sur) macOS

If you don't do that, your 11.X system will not open the app, and will tell you that you need at least MacOS 12 to run it.

**Comment by sajmons** [comment]
@jordisese thank you for your suggestion. With next version the LSMinimumSystemVersion seting wil have value of 11.
